Будем предсказывать институт, где учится студент (признак "Your unstitute") по баллам, на которые он написал ЕГЭ. Баллы за ЕГЭ занимают в нашей таблице столбцы с номерами 6-16. Чтобы из исходной таблицы выбрать только указанные столбцы нужно выполнить команду df_test.iloc[:,6:17] - это и будет таблица, в которой остались только столбцы с результатами ЕГЭ.

Натренируйте модель GradientBoostingClassifier(random_state=0) для предсказания признака "Your unstitute" и запустите ее на тестовой выборке student_test.csv

В окошко ответа запишите количество экономистов, которые были детектированы алгоритмом как математики.



In [23]:
#подключаю гуглдиск
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [16]:
#import frameworks
import pandas as pd
import seaborn as sns
from sklearn.ensemble import GradientBoostingClassifier #подключение Бустинга

In [17]:
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/students.csv', delimiter=',')

In [18]:
df_cut= df.iloc[:,6:17]

In [19]:
model=GradientBoostingClassifier(random_state=0) 
model.fit(df.iloc[:,6:17].values.reshape(-1,11), y=df['Your insitute'].values)

GradientBoostingClassifier(random_state=0)

In [20]:
# загружаем данные тестовой выборки
df_test=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/students_test.csv', delimiter=',')

In [21]:
df_test['Predicted']=model.predict(df_test.iloc[:,6:17].values.reshape(-1,11))

In [22]:
pd.crosstab(df_test['Predicted'], df_test['Your insitute'])

Your insitute                                 Другое  \
Predicted                                              
Другое                                             1   
Естественный (биология-химия-физика-технари)       3   
Математический и ИТ                                1   
Педагогический                                     1   
СоцГум                                             0   
Экономический                                      1   
Юридический                                        0   

Your insitute                                 Естественный (биология-химия-физика-технари)  \
Predicted                                                                                    
Другое                                                                                   3   
Естественный (биология-химия-физика-технари)                                            10   
Математический и ИТ                                                                      7   
Педагогический                                                                           3   
СоцГум                                                                                   0   
Экономический                                                                            0   
Юридический                                                                              0   

Your insitute                                 Математический и ИТ  \
Predicted                                                           
Другое                                                          0   
Естественный (биология-химия-физика-технари)                    0   
Математический и ИТ                                            30   
Педагогический                                                  2   
СоцГум                                                          2   
Экономический                                                   2   
Юридический                                                     0   

Your insitute                                 Педагогический  СоцГум  \
Predicted                                                              
Другое                                                     2       1   
Естественный (биология-химия-физика-технари)               2       0   
Математический и ИТ                                        2       0   
Педагогический                                             1       1   
СоцГум                                                     0       7   
Экономический                                              1       0   
Юридический                                                0       0   

Your insitute                                 Экономический  Юридический  
Predicted                                                                 
Другое                                                    0            0  
Естественный (биология-химия-физика-технари)              0            0  
Математический и ИТ                                       8            0  
Педагогический                                            2            0  
СоцГум                                                    0            0  
Экономический                                             3            1  
Юридический                                               0            1

In [14]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(df_test['Predicted'], df_test['Your insitute'])

(array([0.14285714, 0.43478261, 0.83333333, 0.125     , 0.77777778,
        0.23076923, 0.5       ]),
 array([0.14285714, 0.66666667, 0.625     , 0.1       , 0.77777778,
        0.375     , 1.        ]),
 array([0.14285714, 0.52631579, 0.71428571, 0.11111111, 0.77777778,
        0.28571429, 0.66666667]),
 array([ 7, 15, 48, 10,  9,  8,  1]))